version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rust_api_db
      - RUST_LOG=debug
      - HOST=0.0.0.0
      - PORT=8080
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rust_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
